info:
  name: Upsert Tag
  type: http
  seq: 3
  tags:
    - traggo

http:
  method: POST
  url: "{{baseUrl}}/traggo/tag"
  body:
    type: json
    data: |-
      {
        "name": "test",
        "color": "#AAAAAA"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Successful Response
    request:
      url: "{{baseUrl}}/traggo/version"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: "{}"
  - name: "200"
    request:
      url: "{{baseUrl}}/traggo/version"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: date
          value: Tue, 02 Jun 2026 22:56:55 GMT
        - name: server
          value: uvicorn
        - name: content-length
          value: "28"
        - name: content-type
          value: application/json
      body:
        type: json
        data: |-
          {
            "version": {
              "name": "0.8.3"
            }
          }
